import { FIBONACCI, FRAME, PRIMES } from '../constants.js';
import type { FilterSpec, Feasibility, FeasibilityViolation, Game, Range } from '../types.js';
const inRange=(v:number,r?:Range)=>!r || (r.min===undefined||v>=r.min)&&(r.max===undefined||v<=r.max);
export class FilterEngine {
  check(game:Game, f:FilterSpec):boolean { const s=new Set(game); const sorted=[...game].sort((a,b)=>a-b); let run=sorted.length?1:0,maxRun=run; for(let i=1;i<sorted.length;i++){run=sorted[i]===sorted[i-1]+1?run+1:1;maxRun=Math.max(maxRun,run);} const vals=[['evens',sorted.filter(n=>n%2===0).length,f.evens],['primes',sorted.filter(n=>PRIMES.has(n)).length,f.primes],['fibonacci',sorted.filter(n=>FIBONACCI.has(n)).length,f.fibonacci],['sum',sorted.reduce((a,b)=>a+b,0),f.sum],['frame',sorted.filter(n=>FRAME.has(n)).length,f.frame]] as const; return vals.every(([,v,r])=>inRange(v,r)) && (f.maxConsecutiveRun===undefined||maxRun<=f.maxConsecutiveRun) && (f.maxPopularityScore===undefined||f.maxPopularityScore>=0) && (!f.repeatsFromPrevious || (()=>{const hits=sorted.filter(n=>f.repeatsFromPrevious?.previousDraw.includes(n)).length; return inRange(hits,f.repeatsFromPrevious);})()); }
  checkFeasibility(input:{size:number;pool:readonly number[];fixed:readonly number[];filters:FilterSpec}):Feasibility { const {size,pool,fixed,filters}=input; const violations:FeasibilityViolation[]=[]; if(fixed.length>size) violations.push({constraint:'fixedNumbers',reason:'MORE_FIXED_THAN_SIZE'}); if(pool.length<size) violations.push({constraint:'excludedNumbers',reason:'POOL_TOO_SMALL'}); const candidates=pool.filter(n=>!fixed.includes(n)); const free=size-fixed.length;
    const envelope=(name:string,target:Set<number>,r?:Range)=>{if(!r)return;const fixedCount=fixed.filter(n=>target.has(n)).length;const available=candidates.filter(n=>target.has(n)).length;const outside=candidates.filter(n=>!target.has(n)).length;const min=Math.max(fixedCount,size-outside);const max=Math.min(size,fixedCount+available);if((r.max!==undefined&&r.max<min)||(r.min!==undefined&&r.min>max))violations.push({constraint:name,reason:'OUT_OF_ACHIEVABLE_RANGE',requested:r,achievable:{min,max}});};
    envelope('evens',new Set(pool.filter(n=>n%2===0)),filters.evens); envelope('primes',PRIMES,filters.primes); envelope('fibonacci',FIBONACCI,filters.fibonacci); envelope('frame',FRAME,filters.frame);
    if(filters.sum){const asc=[...candidates].sort((a,b)=>a-b);const low=free>0?asc.slice(0,free):[];const high=free>0?asc.slice(Math.max(0,asc.length-free)):[];const min=fixed.reduce((a,b)=>a+b,0)+low.reduce((a,b)=>a+b,0);const max=fixed.reduce((a,b)=>a+b,0)+high.reduce((a,b)=>a+b,0);if((filters.sum.max!==undefined&&filters.sum.max<min)||(filters.sum.min!==undefined&&filters.sum.min>max))violations.push({constraint:'sum',reason:'OUT_OF_ACHIEVABLE_RANGE',requested:filters.sum,achievable:{min,max}});}
    return {feasible:violations.length===0,violations}; }
}
