import { COLUMNS, DIAGONALS, ROWS, PRIMES } from '../constants.js';
import type { Game, MatchedPattern, PopularityAssessment } from '../types.js';
const specs = [
  ['LONG_CONSECUTIVE_RUN','geometric',0.45], ['FULL_ROW','geometric',0.40], ['FULL_COLUMN','geometric',0.40], ['FULL_DIAGONAL','geometric',0.35], ['HALF_PLAYSLIP','geometric',0.40], ['CORNERS_AND_CENTER','geometric',0.25], ['MULTIPLES_OF_FIVE','arithmetic',0.25], ['MIRRORED_AROUND_13','arithmetic',0.20], ['CALENDAR_HEAVY','calendar',0.30], ['EXTREME_PRIME_COUNT','compositional',0.10],
] as const;
export class PopularityScorer {
  score(game: Game): PopularityAssessment { const s=new Set(game); const matched:MatchedPattern[]=[]; const hasRun=[...s].sort((a,b)=>a-b).some((n, i, xs)=>i>=5 && xs[i-5]===n-5); if(hasRun) matched.push({key:'LONG_CONSECUTIVE_RUN',group:'geometric',weight:.45});
    if(ROWS.some(r=>r.every(n=>s.has(n)))) matched.push({key:'FULL_ROW',group:'geometric',weight:.4}); if(COLUMNS.some(r=>r.every(n=>s.has(n)))) matched.push({key:'FULL_COLUMN',group:'geometric',weight:.4}); if(DIAGONALS.some(r=>r.every(n=>s.has(n)))) matched.push({key:'FULL_DIAGONAL',group:'geometric',weight:.35}); if([...s].filter(n=>n<=12).length>=s.size-1 || [...s].filter(n=>n>=13).length>=s.size-1) matched.push({key:'HALF_PLAYSLIP',group:'geometric',weight:.4}); if([1,5,21,25,13].every(n=>s.has(n))) matched.push({key:'CORNERS_AND_CENTER',group:'geometric',weight:.25}); if([...s].filter(n=>n%5===0).length>=4) matched.push({key:'MULTIPLES_OF_FIVE',group:'arithmetic',weight:.25}); if([...s].every(n=>s.has(26-n))) matched.push({key:'MIRRORED_AROUND_13',group:'arithmetic',weight:.2}); if([...s].filter(n=>n<=12).length>=12) matched.push({key:'CALENDAR_HEAVY',group:'calendar',weight:.3}); const p=[...s].filter(n=>PRIMES.has(n)).length; if(p>=7||p<=2) matched.push({key:'EXTREME_PRIME_COUNT',group:'compositional',weight:.1});
    const groups=new Map<string,number>(); for(const x of matched) groups.set(x.group,Math.max(groups.get(x.group)??0,x.weight)); let complement=1; for(const w of groups.values()) complement*=1-w; return {score:Number((1-complement).toFixed(4)),matchedPatterns:matched,confidence:'heuristic'}; }
}
