'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { analyzeGames, getFilters, parseNumbers, validateAndAnalyzeBatch, type FilterCatalog, type GeneratedResponse } from '@/lib/api';

export function FiltersPage() {
  const router = useRouter(); const [catalog, setCatalog] = useState<FilterCatalog>(); const [quantity, setQuantity] = useState(5); const [numbersPerGame, setNumbersPerGame] = useState(15); const [fixed, setFixed] = useState(''); const [excluded, setExcluded] = useState(''); const [sumMin, setSumMin] = useState(''); const [sumMax, setSumMax] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { getFilters().then(setCatalog).catch(reason => setError(reason instanceof Error ? reason.message : 'Não foi possível carregar os filtros.')); }, []);
  async function submit() { setError(''); const fixedNumbers = parseNumbers(fixed); const excludedNumbers = parseNumbers(excluded); if (fixedNumbers.some(n => excludedNumbers.includes(n))) { setError('Uma dezena não pode ser fixa e excluída ao mesmo tempo.'); return; } setLoading(true); try { const response = await (await import('@/lib/api')).generateFiltered({ quantity, numbersPerGame, fixedNumbers, excludedNumbers, filters: { ...(sumMin || sumMax ? { sum: { ...(sumMin ? { min: Number(sumMin) } : {}), ...(sumMax ? { max: Number(sumMax) } : {}) } } : {}) } }); const validated = await validateAndAnalyzeBatch(response); sessionStorage.setItem('lotzy:validated-games', JSON.stringify(validated)); router.push('/analisar'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível gerar com os filtros.'); } finally { setLoading(false); } }
  return <PageShell eyebrow="01 · Filtros" title="Escolha as restrições." intro="Ajuste somente os filtros oferecidos pela API. A natureza e as advertências de cada filtro vêm do catálogo, sem promessas históricas."><div className="paper-card"><div className="controls"><label>Quantidade<input type="number" min={1} max={100} value={quantity} onChange={event => setQuantity(Math.min(100, Math.max(1, Number(event.target.value))))} /></label><label>Dezenas por jogo<select value={numbersPerGame} onChange={event => setNumbersPerGame(Number(event.target.value))}>{[15,16,17,18,19,20].map(number => <option key={number}>{number}</option>)}</select></label></div><div className="filter-grid"><label>Dezenas fixas<input placeholder="Ex.: 1, 7, 13" value={fixed} onChange={event => setFixed(event.target.value)} /><small>Serão incluídas em todos os jogos.</small></label><label>Dezenas excluídas<input placeholder="Ex.: 4, 9, 22" value={excluded} onChange={event => setExcluded(event.target.value)} /><small>Não serão usadas na geração.</small></label><label>Soma mínima<input type="number" placeholder="Ex.: 170" value={sumMin} onChange={event => setSumMin(event.target.value)} /></label><label>Soma máxima<input type="number" placeholder="Ex.: 220" value={sumMax} onChange={event => setSumMax(event.target.value)} /></label></div>{catalog?.data.map(item => <div className="catalog-row" key={item.key}><div><strong>{item.label}</strong><span className="tag">{item.nature}</span></div><p>{item.note ?? 'Disponível conforme o contrato da API.'}{item.deprecationHint ? ` ${item.deprecationHint}` : ''}</p></div>)}{error && <div className="error" role="alert">{error}</div>}<button className="btn btn-primary" type="button" onClick={submit} disabled={loading}>{loading ? 'Gerando…' : 'Gerar com filtros'}</button></div></PageShell>;
}

export function AnalyzePage() { const [payload, setPayload] = useState<{ batch: GeneratedResponse; analysis: Awaited<ReturnType<typeof analyzeGames>> }>(); useEffect(() => { const raw = sessionStorage.getItem('lotzy:validated-games'); if (raw) try { setPayload(JSON.parse(raw)); } catch { /* estado vazio */ } }, []); return <PageShell eyebrow="03 · Analisar" title="Leia o lote sem superestimar o acaso." intro="A análise mostra métricas calculadas pela API e mantém o aviso de que filtros e popularidade não aumentam a probabilidade de premiação.">{payload ? <><div className="stat-grid"><div className="stat"><span>Soma média</span><b>{payload.analysis.aggregate.meanSum.toFixed(1)}</b></div><div className="stat"><span>Desvio da soma</span><b>{payload.analysis.aggregate.stdDevSum.toFixed(1)}</b></div><div className="stat"><span>Popularidade média</span><b>{payload.analysis.aggregate.meanPopularity.toFixed(2)}</b></div></div><div className="paper-card" style={{marginTop:24}}><h2>Jogos validados</h2><div className="result-list">{payload.analysis.data.map((entry, index) => <div className="game-row" key={`${index}-${entry.game.join('-')}`}><span className="game-index">{String(index + 1).padStart(2, '0')}</span><div className="mini-grid">{entry.game.map(number => <span className="mini-number" key={number}>{String(number).padStart(2, '0')}</span>)}</div><span className="status">soma {entry.metrics.sum}</span></div>)}</div></div><div className="disclaimer"><p>{payload.batch.disclaimer}</p></div></> : <div className="empty"><div><strong>Nenhum lote validado.</strong><p>Use o gerador para iniciar o fluxo.</p></div></div>}</PageShell>; }

export function HelpPage() { return <PageShell eyebrow="Ajuda" title="Como usar o Lotzy." intro="O app organiza combinações da Lotofácil com transparência. Ele não registra apostas, não prevê sorteios e não oferece garantia de acerto."><div className="page-grid"><article className="paper-card"><span className="eyebrow">Gerar</span><h2>Gere um lote</h2><p>Escolha a quantidade e o número de dezenas por jogo. Para controlar dezenas fixas, excluídas ou a faixa de soma, abra <strong>Filtros</strong>.</p></article><article className="paper-card"><span className="eyebrow">Validar</span><h2>Validação automática</h2><p>Todo lote gerado é validado automaticamente antes de aparecer na análise. As métricas descrevem as combinações e não alteram suas probabilidades.</p></article><article className="paper-card"><span className="eyebrow">Analisar</span><h2>Interprete métricas</h2><p>Veja soma média, dispersão, popularidade e diversidade. Essas medidas descrevem o lote; não alteram as probabilidades do sorteio.</p></article><article className="paper-card"><span className="eyebrow">Responsabilidade</span><h2>Use com limite</h2><p>Os jogos precisam ser registrados nos canais oficiais para terem validade. Aposte apenas o que puder perder.</p></article></div></PageShell>; }

function PageShell({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) { return <main className="main"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p><div style={{marginTop:30}}>{children}</div></main>; }
