'use client';
import { useState } from 'react';
import { analyzeGames, bankrollCheck, checkGames, validateGame } from '@/lib/api';
import { PlayslipGrid } from '@/components/PlayslipGrid';

export function ValidatePage() { const [game, setGame] = useState<number[]>([]); const [result, setResult] = useState<unknown>(); return <PageShell eyebrow="Validar volante" title="Uma combinação, com contexto." intro="Confirme tamanho, métricas e avisos sem transformar uma nota estatística em erro."><PlayslipGrid onChange={setGame} /><button className="btn btn-primary" style={{marginTop:18}} onClick={async()=>setResult(await validateGame(game))}>Validar esta combinação</button>{result !== undefined && <pre className="paper-card" style={{whiteSpace:'pre-wrap',marginTop:18}}>{JSON.stringify(result,null,2)}</pre>}</PageShell>; }
export function AnalyzePage() { const [text,setText]=useState('1,2,3,4,5,6,7,8,9,10,11,12,13,14,15'); const [result,setResult]=useState<unknown>(); return <PageShell eyebrow="Analisar lote" title="Veja a distribuição das suas combinações." intro="O painel mostra cobertura e sobreposição do lote. Não compara com uma distribuição histórica."><textarea value={text} onChange={e=>setText(e.target.value)} rows={6} style={{width:'100%',padding:14,borderRadius:12,border:'1px solid var(--line)',background:'var(--paper)',color:'var(--graphite)'}} /><button className="btn btn-primary" style={{marginTop:18}} onClick={async()=>{const game=text.split(',').map(Number).filter(Boolean);setResult(await analyzeGames([game]));}}>Analisar lote</button>{result !== undefined && <pre className="paper-card" style={{whiteSpace:'pre-wrap',marginTop:18,overflow:'auto'}}>{JSON.stringify(result,null,2)}</pre>}</PageShell>; }
export function CheckPage() { const [drawn,setDrawn]=useState('1,2,3,4,5,6,7,8,9,10,11,12,13,14,15'); const [result,setResult]=useState<unknown>(); return <PageShell eyebrow="Conferir" title="Confira sem inventar premiação." intro="As faixas 14 e 15 são pari-mutuel: o valor depende do rateio do concurso e não será fabricado pela interface."><input value={drawn} onChange={e=>setDrawn(e.target.value)} style={{width:'100%'}} /><button className="btn btn-primary" style={{marginTop:18}} onClick={async()=>{const nums=drawn.split(',').map(Number).filter(Boolean);setResult(await checkGames(nums,[nums]));}}>Conferir jogo</button>{result !== undefined && <pre className="paper-card" style={{whiteSpace:'pre-wrap',marginTop:18}}>{JSON.stringify(result,null,2)}</pre>}</PageShell>; }
export function FiltersPage() { return <PageShell eyebrow="Filtros" title="Critérios vêm do catálogo da API." intro="A interface não chama nenhuma faixa de 'ideal'. O backend fornece a natureza, a nota e as ressalvas de cada filtro. A próxima etapa é carregar o catálogo em tempo real."><div className="paper-card"><h2>Diagnóstico honesto</h2><p>Quando a API devolver 206, o resultado parcial será tratado como sucesso com ressalva. Em 422, a interface deve mostrar a faixa alcançável, não apenas uma mensagem genérica.</p><span className="status">Sem promessa de padrão vencedor</span></div></PageShell>; }
export function ToolsPage() { const [budget,setBudget]=useState(100); const [months,setMonths]=useState(6); const [result,setResult]=useState<unknown>(); return <PageShell eyebrow="Ferramentas" title="Planeje o limite, não o prêmio." intro="Projeções informacionais ajudam a visualizar orçamento e perda esperada. Elas não constituem recomendação."><div className="controls"><label>Orçamento mensal (R$)<input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Horizonte (meses)<input type="number" value={months} onChange={e=>setMonths(Number(e.target.value))}/></label><button className="btn btn-primary" onClick={async()=>setResult(await bankrollCheck(budget*100,months))}>Calcular projeção</button></div>{result !== undefined && <pre className="paper-card" style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result,null,2)}</pre>}</PageShell>; }
export function WalletPage() { return <PageShell eyebrow="Carteira local" title="Seus jogos ficam no navegador." intro="A carteira usa armazenamento local versionado. Nada é enviado a terceiros; exportação e limpeza ficam sob seu controle."><div className="paper-card"><h2>Carteira v1</h2><p>A estrutura está preparada para persistir jogos validados com schema e descartar dados corrompidos com aviso.</p><button className="btn btn-secondary">Importar JSON</button> <button className="btn btn-danger">Limpar carteira</button></div></PageShell>; }
function PageShell({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:React.ReactNode}) { return <main className="main"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p><div style={{marginTop:30}}>{children}</div></main>; }
