'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { generateRandom, type GeneratedResponse, formatMoney } from '@/lib/api';
import { PlayslipGrid } from '@/components/PlayslipGrid';

function GameRow({ game, index }: { game: number[]; index: number }) { return <div className="game-row"><span className="game-index">{String(index + 1).padStart(2, '0')}</span><div className="mini-grid">{game.map(number => <span className="mini-number" key={number}>{String(number).padStart(2, '0')}</span>)}</div></div>; }
export default function HomePage() {
  const router = useRouter();
  const [quantity, setQuantity] = useState(5); const [numbersPerGame, setNumbersPerGame] = useState(15); const [result, setResult] = useState<GeneratedResponse>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit() { setLoading(true); setError(''); try { const generated = await generateRandom(quantity, numbersPerGame); sessionStorage.setItem('lotzy:pending-games', JSON.stringify(generated)); router.push('/validar'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível gerar os jogos.'); } finally { setLoading(false); } }
  return <main className="main"><div className="intro"><div><span className="eyebrow">Geração responsável · Lotofácil</span><h1>Marque o papel. Entenda o jogo.</h1><p>Gere combinações uniformes e revise cada lote antes de exibi-lo. O Lotzy organiza escolhas; não prevê sorteios.</p></div><div className="hero-card"><span className="eyebrow" style={{color:'#8bb9f5'}}>Fluxo do produto</span><div className="metric">01 <small>gerar</small></div><p>Depois de gerar, a tela de validação confirma o lote e encaminha para o resultado.</p></div></div><div className="paper-card"><div className="controls"><label>Quantidade<input type="number" min={1} max={500} value={quantity} onChange={e => setQuantity(Math.min(500, Math.max(1, Number(e.target.value))))} /></label><label>Dezenas por jogo<select value={numbersPerGame} onChange={e => setNumbersPerGame(Number(e.target.value))}>{[15,16,17,18,19,20].map(n => <option key={n} value={n}>{n} dezenas</option>)}</select></label><button className="btn btn-primary" onClick={submit} disabled={loading}>{loading ? 'Gerando…' : 'Gerar jogos'}</button><button className="btn btn-secondary" type="button" onClick={() => router.push('/filtros')}>Usar filtros</button></div>{error && <div className="error" role="alert">{error}</div>}<div className="disclaimer"><p><strong>Antes de gerar:</strong> cada combinação tem a mesma probabilidade. Evitar padrões populares pode afetar rateio, mas não aumenta a chance de acerto.</p></div></div><section className="grid-layout" style={{marginTop:24}}><PlayslipGrid /><div className="paper-card"><div className="section-heading"><div><span className="eyebrow">Prévia</span><h2>O resultado aparece após validar</h2></div>{result && <span className="status">{result.meta.generatedQuantity} jogos</span>}</div>{result ? <><div className="stat-grid" style={{marginBottom:16}}><div className="stat"><span>Custo do lote</span><b>{formatMoney(result.cost.totalCents * result.meta.generatedQuantity)}</b></div><div className="stat"><span>Apostas simples</span><b>{result.cost.simpleBets * result.meta.generatedQuantity}</b></div><div className="stat"><span>Dezenas</span><b>{result.meta.numbersPerGame}</b></div></div><div className="result-list">{result.data.map((entry: { game: number[] }, index: number) => <GameRow key={`${index}-${entry.game.join('-')}`} game={entry.game} index={index} />)}</div></> : <div className="empty"><div><strong>O resultado é o herói desta tela.</strong><p>Escolha o tamanho do lote ou abra os filtros para começar.</p></div></div>}</div></section></main>;
}
