'use client';
import { useEffect, useState } from 'react';
import { fetchHistoryStats, type HistoryResponse } from '@/lib/api';
import { PlayslipGrid } from '@/components/PlayslipGrid';

function decimal(value: number) { return new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(value); }
function Distribution({ stats }: { stats: HistoryResponse['data'] }) {
  const points = [['p10', stats.sumDistribution.percentiles.p10], ['p25', stats.sumDistribution.percentiles.p25], ['mediana', stats.sumDistribution.percentiles.p50], ['p75', stats.sumDistribution.percentiles.p75], ['p90', stats.sumDistribution.percentiles.p90]] as const;
  const min = stats.sumDistribution.min; const max = stats.sumDistribution.max;
  return <div className="distribution" aria-label="Percentis da soma dos concursos"><div className="distribution-line" />{points.map(([name, value]) => <div className="distribution-point" key={name} style={{ left: `${((value - min) / Math.max(max - min, 1)) * 100}%` }}><span className="distribution-dot" /><span className="distribution-label"><b>{name}</b>{value}</span></div>)}<div className="distribution-axis"><span>{min}</span><span>média {decimal(stats.sumDistribution.mean)}</span><span>{max}</span></div></div>;
}
export default function HistoryPage() {
  const [response, setResponse] = useState<HistoryResponse>(); const [error, setError] = useState('');
  useEffect(() => { fetchHistoryStats().then(setResponse).catch(e => setError(e instanceof Error ? e.message : 'Não foi possível carregar o histórico.')); }, []);
  if (error) return <main className="main"><div className="error" role="alert">{error}</div></main>;
  if (!response) return <main className="main"><p aria-live="polite">Carregando estatísticas históricas…</p></main>;
  const { data: stats } = response;
  return <main className="main"><div className="intro"><div><span className="eyebrow">Arquivo descritivo · Lotofácil</span><h1>O que já aconteceu, sem tentar adivinhar.</h1><p>Explore a distribuição observada em {stats.drawCount.toLocaleString('pt-BR')} concursos. Estas métricas resumem o passado; não identificam dezenas mais prováveis nem mudam a chance de uma combinação.</p></div><div className="hero-card"><span className="eyebrow" style={{ color: '#8bb9f5' }}>Escopo da leitura</span><div className="metric">{stats.drawCount.toLocaleString('pt-BR')} <small>concursos analisados</small></div><p>O histórico é um retrato estatístico, não um mecanismo de previsão.</p></div></div><div className="disclaimer"><p><strong>Transparência:</strong> em sorteios independentes, todas as combinações válidas têm a mesma probabilidade. Use a página para entender dados, não para buscar vantagem preditiva.</p></div><section className="grid-layout"><PlayslipGrid heatmapValues={stats.frequency} readOnly label="Mapa de calor da frequência histórica" /><div className="paper-card"><span className="eyebrow">Distribuição observada</span><h2>Soma das dezenas</h2><p>Min/Max: {stats.sumDistribution.min}–{stats.sumDistribution.max} · média: {decimal(stats.sumDistribution.mean)}</p><Distribution stats={stats} /><div className="stat-grid" style={{ marginTop: 34 }}><div className="stat"><span>P10 · P90</span><b>{stats.sumDistribution.percentiles.p10}–{stats.sumDistribution.percentiles.p90}</b></div><div className="stat"><span>P25 · P75</span><b>{stats.sumDistribution.percentiles.p25}–{stats.sumDistribution.percentiles.p75}</b></div><div className="stat"><span>Repetições médias</span><b>{decimal(stats.repetitionAverage)}</b></div></div></div></section><section className="paper-card history-metrics"><span className="eyebrow">Médias por concurso</span><h2>Composição observada</h2><div className="stat-grid"><div className="stat"><span>Pares</span><b>{decimal(stats.averages.even)}</b></div><div className="stat"><span>Ímpares</span><b>{decimal(stats.averages.odd)}</b></div><div className="stat"><span>Primos</span><b>{decimal(stats.averages.primes)}</b></div><div className="stat"><span>Moldura</span><b>{decimal(stats.averages.frame)}</b></div></div><p className="muted-note">As médias são referências descritivas do arquivo local e podem mudar quando novos concursos forem adicionados.</p></section><div className="disclaimer"><p>{response.disclaimer}</p></div></main>;
}
